version: '3.9'

services:
  catalogdb:
    container_name: catalogdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
    