version: '3.4'

services:
  catalogdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  postgres_catalog: